#ifndef __CAT_STATUS_H__
#define __CAT_STATUS_H__

enum cat_status {
    CAT_STATUS_UNINITIALIZED = -1,
    CAT_STATUS_SUCCESS = 0,

    CAT_STATUS_CAT_MALLOC_FAILED,
    CAT_STATUS_CAT_READ_FAILED,
    CAT_STATUS_CAT_WRITE_FAILED,
    CAT_STATUS_CAT_OPEN_FAILED,
    CAT_STATUS_CAT_CLOSE_FAILED
};

#endif